RegisterNetEvent('os-kaynine:client:PlayAttackAnimsKaynine', function()
    local ped = PlayerPedId()
    exports['os-utilities']:LoadAnimDict('creatures@rottweiler@melee@', function()
        TaskPlayAnim(ped, 'creatures@rottweiler@melee@', 'dog_attack', 8.0, 8.0, -1, 0, 0, 0, 0, 0)
    end)
    Wait(1000)
    exports['os-utilities']:LoadAnimDict('creatures@rottweiler@indication@', function()
        TaskPlayAnim(ped, 'creatures@rottweiler@indication@', 'indicate_ahead', 8.0, 8.0, -1, 0, 0, 0, 0, 0)
    end)
    Wait(1000)
    ClearPedTasks(ped)
    Melee = false
end)

RegisterNetEvent('os-kaynine:client:PlayAttackAnimsVictim', function(data)
    local ped = NetToPed(data.netId)
    if IsPedAPlayer(ped) then
        ped = PlayerPedId()
        ShakeGameplayCam('SMALL_EXPLOSION_SHAKE', 0.2)
    end
    ClearPedTasksImmediately(ped)
    exports['os-utilities']:LoadAnimDict('creatures@rottweiler@melee@', function()
        TaskPlayAnim(ped, 'creatures@rottweiler@melee@', data.victimAnim, 8.0, 8.0, -1, 0, 0, 0, 0, 0)
    end)
    ApplyDamageToPed(ped, math.random(Config.Damage.min, Config.Damage.max), false)
end)

RegisterNetEvent('os-kaynine:client:PlayAnimsKaynine', function(data)
    local ped = PlayerPedId()
    exports['os-utilities']:LoadAnimDict('creatures@rottweiler@melee@', function()
        TaskPlayAnim(ped, 'creatures@rottweiler@melee@', data.dogAnim, 8.0, 8.0, -1, 0, 0, 0, 0, 0)
    end)
    Wait(2000)
    CreateThread(function()
        local pPos = GetEntityCoords(ped)
        while Pinned do
            local pos = GetEntityCoords(Target)
            local dir = pos - pPos
            local angle = math.deg(math.atan(-dir.x, dir.y))
            angle = angle < 0 and angle + 360 or angle > 360 and angle - 360 or angle
            local rot = GetEntityRotation(ped)
            exports['os-utilities']:LoadAnimDict('creatures@rottweiler@melee@', function()
                TaskPlayAnimAdvanced(ped, 'creatures@rottweiler@melee@', data.dogAnim, pPos, vector3(rot.x, rot.y, angle), 16.0, 8.0, -1, 0, 0.5, 0, 0, 0)
            end)
            Wait(800)
        end
    end)
    PinnedTarget()
end)

RegisterNetEvent('os-kaynine:client:PlayAnimsVictim', function(data)
    local ped = NetToPed(data.netId)
    if IsPedAPlayer(ped) then
        ped = PlayerPedId()
        ShakeGameplayCam('SMALL_EXPLOSION_SHAKE', 0.2)
    end
    ClearPedTasksImmediately(ped)
    exports['os-utilities']:LoadAnimDict('creatures@rottweiler@melee@streamed_core@', function()
        TaskPlayAnimAdvanced(ped, 'creatures@rottweiler@melee@streamed_core@', data.victimAnim, data.attackPos, data.attackRot, 8.0, 8.0, -1, 0, 0, 0, 0)
    end)
    Wait(2000)
    FreezeEntityPosition(ped, true)
    CreateThread(function()
        local coords = GetEntityCoords(ped)
        local rot = GetEntityRotation(ped)
        while Pinned do
            exports['os-utilities']:LoadAnimDict('creatures@rottweiler@melee@streamed_core@', function()
                TaskPlayAnimAdvanced(ped, 'creatures@rottweiler@melee@streamed_core@', data.victimAnim, coords, rot, 16.0, 0.1, -1, 0, 0.5, 0, 0)
            end)
            Wait(800)
        end
    end)
end)

RegisterNetEvent('os-kaynine:client:PlayAnimsFinishedKaynine', function()
    local ped = PlayerPedId()
    exports['os-utilities']:LoadAnimDict('creatures@rottweiler@melee@base@', function()
        TaskPlayAnim(ped, 'creatures@rottweiler@melee@base@', 'hit_from_front', 4.0, 8.0, -1, 2, 0, 0, 0, 0)
    end)
    Wait(1000)
    exports['os-utilities']:LoadAnimDict('creatures@rottweiler@move', function()
        TaskPlayAnim(ped, 'creatures@rottweiler@move', 'dead_left', 4.0, 8.0, Config.StunTime, 2, 0, 0, 0, 0)
    end)
    Wait(Config.StunTime)
    exports['os-utilities']:LoadAnimDict('creatures@rottweiler@getup', function()
        TaskPlayAnim(ped, 'creatures@rottweiler@getup', 'getup_r', 8.0, 8.0, -1, 0, 0, 0, 0, 0)
    end)
end)

RegisterNetEvent('os-kaynine:client:PlayAnimsFinishedVictim', function(netId, dogNetId)
    local _ped = NetToPed(netId)
    local ped = IsPedAPlayer(_ped) and PlayerPedId() or _ped
    FreezeEntityPosition(ped, false)
    exports['os-utilities']:LoadAnimDict('get_up@sat_on_floor@to_stand', function()
        TaskPlayAnim(ped, 'get_up@sat_on_floor@to_stand', 'getup_0', 8.0, 8.0, -1, 0, 0, 0, 0, 0)
    end)
    Wait(1000)
    if not IsPedAPlayer(ped) then TaskSmartFleePed(ped, NetToPed(dogNetId), 100000.0, -1, false, false) end
end)